/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as WelcomeImport } from './routes/welcome'
import { Route as SignUpImport } from './routes/sign-up'
import { Route as SignInImport } from './routes/sign-in'
import { Route as ForgetPasswordImport } from './routes/forget-password'
import { Route as IndexImport } from './routes/index'
import { Route as WelcomeVoiceUploadImport } from './routes/welcome/voice-upload'
import { Route as WelcomeVoiceLibraryImport } from './routes/welcome/voice-library'
import { Route as WelcomeVoiceCloneImport } from './routes/welcome/voice-clone'
import { Route as WelcomeSettingsImport } from './routes/welcome/settings'
import { Route as WelcomeProjectsImport } from './routes/welcome/projects'
import { Route as WelcomeProfileImport } from './routes/welcome/profile'
import { Route as WelcomeDashboardImport } from './routes/welcome/dashboard'

// Create/Update Routes

const WelcomeRoute = WelcomeImport.update({
  id: '/welcome',
  path: '/welcome',
  getParentRoute: () => rootRoute,
} as any)

const SignUpRoute = SignUpImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRoute,
} as any)

const SignInRoute = SignInImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRoute,
} as any)

const ForgetPasswordRoute = ForgetPasswordImport.update({
  id: '/forget-password',
  path: '/forget-password',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const WelcomeVoiceUploadRoute = WelcomeVoiceUploadImport.update({
  id: '/voice-upload',
  path: '/voice-upload',
  getParentRoute: () => WelcomeRoute,
} as any)

const WelcomeVoiceLibraryRoute = WelcomeVoiceLibraryImport.update({
  id: '/voice-library',
  path: '/voice-library',
  getParentRoute: () => WelcomeRoute,
} as any)

const WelcomeVoiceCloneRoute = WelcomeVoiceCloneImport.update({
  id: '/voice-clone',
  path: '/voice-clone',
  getParentRoute: () => WelcomeRoute,
} as any)

const WelcomeSettingsRoute = WelcomeSettingsImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => WelcomeRoute,
} as any)

const WelcomeProjectsRoute = WelcomeProjectsImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => WelcomeRoute,
} as any)

const WelcomeProfileRoute = WelcomeProfileImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => WelcomeRoute,
} as any)

const WelcomeDashboardRoute = WelcomeDashboardImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => WelcomeRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/forget-password': {
      id: '/forget-password'
      path: '/forget-password'
      fullPath: '/forget-password'
      preLoaderRoute: typeof ForgetPasswordImport
      parentRoute: typeof rootRoute
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInImport
      parentRoute: typeof rootRoute
    }
    '/sign-up': {
      id: '/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof SignUpImport
      parentRoute: typeof rootRoute
    }
    '/welcome': {
      id: '/welcome'
      path: '/welcome'
      fullPath: '/welcome'
      preLoaderRoute: typeof WelcomeImport
      parentRoute: typeof rootRoute
    }
    '/welcome/dashboard': {
      id: '/welcome/dashboard'
      path: '/dashboard'
      fullPath: '/welcome/dashboard'
      preLoaderRoute: typeof WelcomeDashboardImport
      parentRoute: typeof WelcomeImport
    }
    '/welcome/profile': {
      id: '/welcome/profile'
      path: '/profile'
      fullPath: '/welcome/profile'
      preLoaderRoute: typeof WelcomeProfileImport
      parentRoute: typeof WelcomeImport
    }
    '/welcome/projects': {
      id: '/welcome/projects'
      path: '/projects'
      fullPath: '/welcome/projects'
      preLoaderRoute: typeof WelcomeProjectsImport
      parentRoute: typeof WelcomeImport
    }
    '/welcome/settings': {
      id: '/welcome/settings'
      path: '/settings'
      fullPath: '/welcome/settings'
      preLoaderRoute: typeof WelcomeSettingsImport
      parentRoute: typeof WelcomeImport
    }
    '/welcome/voice-clone': {
      id: '/welcome/voice-clone'
      path: '/voice-clone'
      fullPath: '/welcome/voice-clone'
      preLoaderRoute: typeof WelcomeVoiceCloneImport
      parentRoute: typeof WelcomeImport
    }
    '/welcome/voice-library': {
      id: '/welcome/voice-library'
      path: '/voice-library'
      fullPath: '/welcome/voice-library'
      preLoaderRoute: typeof WelcomeVoiceLibraryImport
      parentRoute: typeof WelcomeImport
    }
    '/welcome/voice-upload': {
      id: '/welcome/voice-upload'
      path: '/voice-upload'
      fullPath: '/welcome/voice-upload'
      preLoaderRoute: typeof WelcomeVoiceUploadImport
      parentRoute: typeof WelcomeImport
    }
  }
}

// Create and export the route tree

interface WelcomeRouteChildren {
  WelcomeDashboardRoute: typeof WelcomeDashboardRoute
  WelcomeProfileRoute: typeof WelcomeProfileRoute
  WelcomeProjectsRoute: typeof WelcomeProjectsRoute
  WelcomeSettingsRoute: typeof WelcomeSettingsRoute
  WelcomeVoiceCloneRoute: typeof WelcomeVoiceCloneRoute
  WelcomeVoiceLibraryRoute: typeof WelcomeVoiceLibraryRoute
  WelcomeVoiceUploadRoute: typeof WelcomeVoiceUploadRoute
}

const WelcomeRouteChildren: WelcomeRouteChildren = {
  WelcomeDashboardRoute: WelcomeDashboardRoute,
  WelcomeProfileRoute: WelcomeProfileRoute,
  WelcomeProjectsRoute: WelcomeProjectsRoute,
  WelcomeSettingsRoute: WelcomeSettingsRoute,
  WelcomeVoiceCloneRoute: WelcomeVoiceCloneRoute,
  WelcomeVoiceLibraryRoute: WelcomeVoiceLibraryRoute,
  WelcomeVoiceUploadRoute: WelcomeVoiceUploadRoute,
}

const WelcomeRouteWithChildren =
  WelcomeRoute._addFileChildren(WelcomeRouteChildren)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/forget-password': typeof ForgetPasswordRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/welcome': typeof WelcomeRouteWithChildren
  '/welcome/dashboard': typeof WelcomeDashboardRoute
  '/welcome/profile': typeof WelcomeProfileRoute
  '/welcome/projects': typeof WelcomeProjectsRoute
  '/welcome/settings': typeof WelcomeSettingsRoute
  '/welcome/voice-clone': typeof WelcomeVoiceCloneRoute
  '/welcome/voice-library': typeof WelcomeVoiceLibraryRoute
  '/welcome/voice-upload': typeof WelcomeVoiceUploadRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forget-password': typeof ForgetPasswordRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/welcome': typeof WelcomeRouteWithChildren
  '/welcome/dashboard': typeof WelcomeDashboardRoute
  '/welcome/profile': typeof WelcomeProfileRoute
  '/welcome/projects': typeof WelcomeProjectsRoute
  '/welcome/settings': typeof WelcomeSettingsRoute
  '/welcome/voice-clone': typeof WelcomeVoiceCloneRoute
  '/welcome/voice-library': typeof WelcomeVoiceLibraryRoute
  '/welcome/voice-upload': typeof WelcomeVoiceUploadRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/forget-password': typeof ForgetPasswordRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/welcome': typeof WelcomeRouteWithChildren
  '/welcome/dashboard': typeof WelcomeDashboardRoute
  '/welcome/profile': typeof WelcomeProfileRoute
  '/welcome/projects': typeof WelcomeProjectsRoute
  '/welcome/settings': typeof WelcomeSettingsRoute
  '/welcome/voice-clone': typeof WelcomeVoiceCloneRoute
  '/welcome/voice-library': typeof WelcomeVoiceLibraryRoute
  '/welcome/voice-upload': typeof WelcomeVoiceUploadRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forget-password'
    | '/sign-in'
    | '/sign-up'
    | '/welcome'
    | '/welcome/dashboard'
    | '/welcome/profile'
    | '/welcome/projects'
    | '/welcome/settings'
    | '/welcome/voice-clone'
    | '/welcome/voice-library'
    | '/welcome/voice-upload'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forget-password'
    | '/sign-in'
    | '/sign-up'
    | '/welcome'
    | '/welcome/dashboard'
    | '/welcome/profile'
    | '/welcome/projects'
    | '/welcome/settings'
    | '/welcome/voice-clone'
    | '/welcome/voice-library'
    | '/welcome/voice-upload'
  id:
    | '__root__'
    | '/'
    | '/forget-password'
    | '/sign-in'
    | '/sign-up'
    | '/welcome'
    | '/welcome/dashboard'
    | '/welcome/profile'
    | '/welcome/projects'
    | '/welcome/settings'
    | '/welcome/voice-clone'
    | '/welcome/voice-library'
    | '/welcome/voice-upload'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ForgetPasswordRoute: typeof ForgetPasswordRoute
  SignInRoute: typeof SignInRoute
  SignUpRoute: typeof SignUpRoute
  WelcomeRoute: typeof WelcomeRouteWithChildren
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ForgetPasswordRoute: ForgetPasswordRoute,
  SignInRoute: SignInRoute,
  SignUpRoute: SignUpRoute,
  WelcomeRoute: WelcomeRouteWithChildren,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/forget-password",
        "/sign-in",
        "/sign-up",
        "/welcome"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/forget-password": {
      "filePath": "forget-password.tsx"
    },
    "/sign-in": {
      "filePath": "sign-in.tsx"
    },
    "/sign-up": {
      "filePath": "sign-up.tsx"
    },
    "/welcome": {
      "filePath": "welcome.tsx",
      "children": [
        "/welcome/dashboard",
        "/welcome/profile",
        "/welcome/projects",
        "/welcome/settings",
        "/welcome/voice-clone",
        "/welcome/voice-library",
        "/welcome/voice-upload"
      ]
    },
    "/welcome/dashboard": {
      "filePath": "welcome/dashboard.tsx",
      "parent": "/welcome"
    },
    "/welcome/profile": {
      "filePath": "welcome/profile.tsx",
      "parent": "/welcome"
    },
    "/welcome/projects": {
      "filePath": "welcome/projects.tsx",
      "parent": "/welcome"
    },
    "/welcome/settings": {
      "filePath": "welcome/settings.tsx",
      "parent": "/welcome"
    },
    "/welcome/voice-clone": {
      "filePath": "welcome/voice-clone.tsx",
      "parent": "/welcome"
    },
    "/welcome/voice-library": {
      "filePath": "welcome/voice-library.tsx",
      "parent": "/welcome"
    },
    "/welcome/voice-upload": {
      "filePath": "welcome/voice-upload.tsx",
      "parent": "/welcome"
    }
  }
}
ROUTE_MANIFEST_END */
